# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RYO
email: ryovxx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  developer of innovative sonic weapons as OVXX, CEO reptilian of KitterChord, comrade of Twinknation,. ϑ'self does nøt lie passively in wait for us to discover it ︻╦̵̵͇̿̿̿̿══╤─
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

author:
  name   : "Ryan Leo Tz-Tzen"
  avatar : "/assets/images/IMG-20240220-WA0001.jpg"
  bio    : "developer of innovative sonic weapons as OVXX, CEO reptilian of KitterChord, comrade of Twinknation,. ϑ'self does nøt lie passively in wait for us to discover it ︻╦̵̵͇̿̿̿̿══╤─"
  links:
    - label: "φꙩtꙩptiques"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/cryotato"
    - label: "corproart"
      icon: "fab fa-fw fa-behance"
      url: "https://www.behance.net/ryanmeow"
    - label: "slayvery"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ovxx/"   
    - label: "pirate OVXX"
      icon: "fab fa-fw fa-bandcamp"
      url: "https://ovxx.bandcamp.com/"
    - label: "stream OVXX"
      icon: "fab fa-fw fa-spotify"
      url: "https://open.spotify.com/artist/5kysZzGC0WtDlkwSX4P1St"

      

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/cryotato"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@ovxx666"     
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@cryotato"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/cryotato"
    - label: "Bandcamp"
      icon: "fab fa-fw fa-bandcamp"
      url: "https://ovxx.bandcamp.com/"
    - label: "Spotify"
      icon: "fab fa-fw fa-spotify"
      url: "https://open.spotify.com/artist/5kysZzGC0WtDlkwSX4P1St"
    - label: "SoundCloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/poorpupperdrinksbleach"
    - label: "Secret SoundCloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/ovxx2"
    - label: "RateYourMusic"
      icon: "fab fa-fw fa-link"
      url: "https://rateyourmusic.com/~cryotato"
    - label: "Goodreads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://www.goodreads.com/user/show/114414047-rya"
    - label: "Behance"
      icon: "fab fa-fw fa-behance"
      url: "https://www.behance.net/ryanmeow"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ovxx/"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://ryaen.medium.com/"
    - label: "itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://cryotato.itch.io/"
      

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      show_date: true


# wait then wgat the fycj is this.. huh?
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts:
  # - https://unpkg.com/lenis@1.1.6/dist/lenis.min.js # Add Lenis library
  - /assets/js/cursor.js
  - /assets/js/scroll-color-change.js
  # - /assets/js/smooth-scroll.js

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

repository: cryotato/cryotato.github.io

comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOOS_0aQ
    category_name        : Announcements
    category_id          : DIC_kwDOOS_0ac4CpKnF # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 0 # '1' for enabled (default), '0' for disabled
    theme                : light # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

logo: "/assets/images/ryanlogo.svg"
masthead_title: " "

google_site_verification: "wD_He710YLoaY_ipLzU7dMxL1rPo_FkZwSNzyvBkWfY"